### ISSUE TITLE
JDBCConnectionException at api-dev

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/Broker#111]
Tried to create a new user via:
```
curl -X POST "http://api-dev.freme-project.eu/current/user?username=templates&password=temp1234"
```

and got:
```
{
  "exception": "org.springframework.dao.DataAccessResourceFailureException",
  "path": "/user",
  "message": "could not prepare statement; nested exception is org.hibernate.exception.JDBCConnectionException: could not prepare statement",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1444130407586
}
```
Is the MySQL database at Jenkins configured correctly?

**Comment by jnehring** [comment]
It seems that the broker looses the MySQL connection after a while. A quick workaround is to restart freme-dev. 

According to [this document](http://stackoverflow.com/questions/22684807/spring-boot-jpa-configuring-auto-reconnect) I added this bit to the broker configuration in order to auto reconnect the database
```
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1
```

**Comment by jnehring** [comment]
The connection is stable for three days now so I assume this is fixed.
