### ISSUE TITLE
FREME live is using dev endpoint for FREME NER

### ISSUE THREAD

**Issue by m1ci** [freme-project/Broker#163]
Currently, FREME live is using the dev endpoint of FREME NER listening on 8081.
This should be changed to 8080.
See https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/eservices/FremeNER.java#L63

**Comment by jnehring** [comment]
ok i will change this and restart freme-live

**Comment by m1ci** [comment]
It can be nice if you can wait with the restart until https://github.com/freme-project/Documentation/issues/175 and the documentation is updated.

**Comment by jnehring** [comment]
I created a configuration parameter `freme.ner.api-endpoint`. So freme-dev and freme-live have the same code base and only differ in the configuration.

I could not test if it works. I wanted to create a dataset on freme-dev and see if it appears on freme-live but something seems to be wrong:
https://github.com/freme-project/Documentation/issues/177
https://github.com/freme-project/Documentation/issues/176

@m1ci how can we test if it uses the right API?

**Comment by m1ci** [comment]
FREME NER dev is up and running, but if I try http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets/ I get
```
{
  "exception": "eu.freme.broker.exception.ExternalServiceFailedException",
  "path": "/e-entity/freme-ner/datasets/",
  "message": "404 Not Found",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1455273704370
}
```

Can you double-check if there is not smth wrong with the configuration parameter and that it is really used?

**Comment by jnehring** [comment]
I updated the config. Now http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets/ works. But I also have to update the configuration in https://github.com/freme-project/e-Entity/blob/master/src/main/java/eu/freme/eservices/eentity/api/EEntityService.java#L49 on freme-live. Should we create a new issue because the same thing is configured in two places? I think this calls for problems like the one we have right now.

**Comment by jnehring** [comment]
this ticket is no longer valid
